const quoteData={
 clients:['Mariana López','Ana Martínez'],
 recipes:{
  pan:[['Vainilla',182],['Chocolate',205],['Red velvet',225]],
  filling:[['Frutos rojos',126],['Chocolate',154],['Cajeta',118]],
  cover:[['Buttercream vainilla',168],['Ganache',190]],
  cheesecake:[['Clásico',285],['Frutos rojos',335],['Pistacho',395]],
  dessert:[['Galleta NY',18],['Macaron',14],['Beso de cacao',11],['Cheesecake individual',32]]
 },
 products:[
  {id:'cake',name:'Pastel personalizado',type:'cake',margin:55},
  {id:'cheese',name:'Cheesecake',type:'cheese',margin:50},
  {id:'table',name:'Mesa de postres',type:'table',margin:52}
 ]
};
const qmoney=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(+n||0);
const qopts=(arr,val='')=>arr.map((x,i)=>`<option value="${i}" ${String(i)===String(val)?'selected':''}>${x[0]} · ${qmoney(x[1])}</option>`).join('');
const qfield=(label,id,type='text',value='')=>`<label class="field"><span>${label}</span><input id="${id}" type="${type}" value="${value}"></label>`;
const qselect=(label,id,html)=>`<label class="field"><span>${label}</span><select id="${id}">${html}</select></label>`;
function qshell(name,inner,summary='qSummary'){return `<div class="quote-builder card"><div class="quote-head"><div><button class="link-btn" onclick="show('quotes')">← Volver</button><h2>${name}</h2><p class="muted">Configura solo lo necesario; DENYA calcula con las recetas del negocio.</p></div><span class="badge">Borrador</span></div><div class="form-grid quote-meta">${qselect('Cliente','qClient',quoteData.clients.map(x=>`<option>${x}</option>`).join(''))}${qfield('Fecha del evento','qDate','date')}${qfield('Hora','qTime','time')}${qfield('Notas / diseño','qNotes','text')}</div><div class="quote-columns"><div>${inner}</div><aside class="quote-summary" id="${summary}"></aside></div></div>`}
function bindSingle(selector,cb){document.querySelectorAll(selector).forEach(g=>g.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{g.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');cb&&cb(g,b)}))}

window.configureProduct=function(productId=null){
 const p=quoteData.products.find(x=>x.id===productId);
 modal({title:p?'Editar producto':'Configurar producto',saveLabel:p?'Guardar cambios':'Crear producto',body:`<div class="form-grid">${qfield('Nombre','cfgName','text',p?.name||'')}${qselect('Tipo','cfgType','<option value="cake">Pastel configurable</option><option value="cheese">Producto por tamaño</option><option value="table">Mesa de postres</option><option value="simple">Producto simple</option>')}${qfield('Margen objetivo %','cfgMargin','number',p?.margin||55)}${qfield('Descripción','cfgDesc','text','Producto configurable')}</div><div class="config-box"><h3>Recetas del negocio</h3><p class="muted">El negocio elige qué recetas alimentan el cotizador. No usa recetas de DENICAKE.</p><div class="form-grid">${qselect('Receta principal','cfgRecipe','<option>Seleccionar receta...</option><option>Pan de vainilla</option><option>Cheesecake clásico</option><option>Galleta NY</option>')}${qselect('Receta alternativa','cfgAlt','<option>Opcional</option><option>Pan de chocolate</option><option>Cheesecake pistacho</option>')}</div></div><div class="config-box"><h3>Campos visibles al cotizar</h3><div class="check-grid"><label><input type="checkbox" checked> Tamaño / personas</label><label><input type="checkbox" checked> Sabor</label><label><input type="checkbox" checked> Relleno</label><label><input type="checkbox" checked> Cobertura</label><label><input type="checkbox" checked> Extras múltiples</label><label><input type="checkbox" checked> Descuento / cupón</label></div></div>`,onSave:w=>{const name=w.querySelector('#cfgName').value.trim();if(!name)return; if(p){p.name=name;p.margin=+w.querySelector('#cfgMargin').value||55}else quoteData.products.push({id:'custom'+Date.now(),name,type:w.querySelector('#cfgType').value,margin:+w.querySelector('#cfgMargin').value||55});toast('Producto configurado');show('quotes')}})
};

window.cakeQuote=function(){
 title.textContent='Cotizador · Pastel';
 c.innerHTML=qshell('Pastel personalizado',`<section class="step"><div class="step-title"><span>1</span><div><b>Tipo de pastel</b><small>Estructura y altura</small></div></div><div class="chips single" id="cakeType"><button class="chip active">Bajo</button><button class="chip">Alto</button><button class="chip">2 pisos</button><button class="chip">Cupcakes</button></div></section><section class="step"><div class="step-title"><span>2</span><div><b>Tamaño / personas</b><small>Rendimientos configurados por el negocio</small></div></div><div class="chips single" id="cakeSize"><button class="chip" data-add="-90">15 cm · 10–15</button><button class="chip active" data-add="0">20 cm · 20–30</button><button class="chip" data-add="150">25 cm · 35–45</button><button class="chip" data-add="290">30 cm · 50–70</button></div></section><section class="step"><div class="step-title"><span>3</span><div><b>Sabor de pan</b><small>Receta propia</small></div></div>${qselect('Pan','cakePan',qopts(quoteData.recipes.pan))}</section><section class="step"><div class="step-title"><span>4</span><div><b>Relleno</b><small>Receta propia</small></div></div>${qselect('Relleno','cakeFill',qopts(quoteData.recipes.filling))}</section><section class="step"><div class="step-title"><span>5</span><div><b>Cobertura</b><small>Receta propia</small></div></div>${qselect('Cobertura','cakeCover',qopts(quoteData.recipes.cover))}</section><section class="step"><div class="step-title"><span>6</span><div><b>Extras</b><small>Puedes seleccionar varios</small></div></div><div class="chips multi" id="cakeExtras"><button class="chip" data-add="35">Topper +$35</button><button class="chip" data-add="95">Fondant +$95</button><button class="chip" data-add="70">Flores +$70</button><button class="chip" data-add="45">Perlas +$45</button><button class="chip" data-add="120">Figura +$120</button></div><div class="form-grid compact">${qfield('Extra libre','cakeExtra')}${qfield('Costo extra','cakeExtraCost','number','0')}</div></section><section class="step"><div class="step-title"><span>7</span><div><b>Ajuste final</b></div></div><div class="form-grid compact">${qfield('Descuento / cupón %','cakeDiscount','number','0')}${qfield('Precio manual (opcional)','cakeManual','number','0')}</div></section>`,'cakeSummary');
 let sizeAdd=0,extraAdd=0;
 function calc(){const pan=quoteData.recipes.pan[+document.querySelector('#cakePan').value][1],fill=quoteData.recipes.filling[+document.querySelector('#cakeFill').value][1],cover=quoteData.recipes.cover[+document.querySelector('#cakeCover').value][1],free=+document.querySelector('#cakeExtraCost').value||0;const cost=pan+fill+cover+95+sizeAdd+extraAdd+free;let price=Math.round(cost/.45);price=Math.round(price*(1-(+document.querySelector('#cakeDiscount').value||0)/100));const manual=+document.querySelector('#cakeManual').value||0;if(manual>0)price=manual;const profit=price-cost;document.querySelector('#cakeSummary').innerHTML=`<h3>Resumen</h3><div class="summary-line"><span>Recetas</span><b>${qmoney(pan+fill+cover)}</b></div><div class="summary-line"><span>Empaque / operación</span><b>${qmoney(95)}</b></div><div class="summary-line"><span>Extras</span><b>${qmoney(sizeAdd+extraAdd+free)}</b></div><div class="summary-line"><span>Ganancia</span><b>${qmoney(profit)}</b></div><div class="summary-line"><span>Margen real</span><b>${price?Math.round(profit/price*100):0}%</b></div><div class="summary-total"><span>Precio sugerido</span><strong>${qmoney(price)}</strong></div><button class="secondary full" onclick="toast('Vista PDF demo')">Vista PDF</button><button class="primary full" style="margin-top:8px" onclick="toast('Cotización guardada')">Guardar cotización</button>`}
 bindSingle('#cakeType');bindSingle('#cakeSize',(g,b)=>{sizeAdd=+b.dataset.add||0;calc()});document.querySelectorAll('#cakeExtras .chip').forEach(b=>b.onclick=()=>{b.classList.toggle('active');extraAdd=[...document.querySelectorAll('#cakeExtras .active')].reduce((s,x)=>s+(+x.dataset.add||0),0);calc()});['cakePan','cakeFill','cakeCover','cakeExtraCost','cakeDiscount','cakeManual'].forEach(id=>document.querySelector('#'+id).addEventListener('input',calc));calc();
};

window.cheesecakeQuote=function(){
 title.textContent='Cotizador · Cheesecake';
 c.innerHTML=qshell('Cheesecake',`<section class="step"><div class="step-title"><span>1</span><div><b>Sabor</b><small>Ligado a receta propia</small></div></div>${qselect('Receta','cheeseRecipe',qopts(quoteData.recipes.cheesecake))}</section><section class="step"><div class="step-title"><span>2</span><div><b>Tamaño</b></div></div><div class="chips single" id="cheeseSize"><button class="chip active" data-f="1">Chico · 8–10</button><button class="chip" data-f="1.35">Mediano · 12–15</button><button class="chip" data-f="1.75">Grande · 18–22</button></div></section><section class="step"><div class="form-grid compact">${qfield('Cantidad','cheeseQty','number','1')}${qfield('Extra / decoración','cheeseExtra','number','0')}${qfield('Descuento %','cheeseDiscount','number','0')}</div></section>`,'cheeseSummary');let f=1;function calc(){const r=quoteData.recipes.cheesecake[+document.querySelector('#cheeseRecipe').value],qty=Math.max(1,+document.querySelector('#cheeseQty').value||1),cost=r[1]*f*qty+(+document.querySelector('#cheeseExtra').value||0);let price=Math.round(cost/.5);price=Math.round(price*(1-(+document.querySelector('#cheeseDiscount').value||0)/100));document.querySelector('#cheeseSummary').innerHTML=`<h3>Resumen</h3><div class="summary-line"><span>${r[0]} × ${qty}</span><b>${qmoney(cost)}</b></div><div class="summary-line"><span>Ganancia</span><b>${qmoney(price-cost)}</b></div><div class="summary-total"><span>Total</span><strong>${qmoney(price)}</strong></div><button class="primary full" onclick="toast('Cotización guardada')">Guardar cotización</button>`}bindSingle('#cheeseSize',(g,b)=>{f=+b.dataset.f||1;calc()});['cheeseRecipe','cheeseQty','cheeseExtra','cheeseDiscount'].forEach(id=>document.querySelector('#'+id).addEventListener('input',calc));calc();
};

window.dessertTableQuote=function(){
 title.textContent='Cotizador · Mesa de postres';
 c.innerHTML=qshell('Mesa de postres',`<section class="step"><div class="step-title"><span>1</span><div><b>Postres</b><small>Agrega tantas recetas como necesites</small></div></div><div id="dessertLines"></div><button class="secondary" id="addDessert">+ Agregar postre</button></section><section class="step"><div class="step-title"><span>2</span><div><b>Servicio</b></div></div><div class="form-grid compact">${qfield('Montaje / mobiliario','tableSetup','number','0')}${qfield('Entrega','tableDelivery','number','0')}${qfield('Descuento %','tableDiscount','number','0')}</div></section>`,'tableSummary');let lines=[{r:0,q:20},{r:1,q:20}];function draw(){const box=document.querySelector('#dessertLines');box.innerHTML=lines.map((l,i)=>`<div class="dessert-line"><select data-i="${i}" data-k="r">${qopts(quoteData.recipes.dessert,l.r)}</select><input data-i="${i}" data-k="q" type="number" min="1" value="${l.q}"><button class="icon-btn" data-rm="${i}">×</button></div>`).join('');box.querySelectorAll('[data-k]').forEach(x=>x.oninput=()=>{lines[+x.dataset.i][x.dataset.k]=+x.value||0;calc()});box.querySelectorAll('[data-rm]').forEach(x=>x.onclick=()=>{lines.splice(+x.dataset.rm,1);draw()});calc()}function calc(){const products=lines.reduce((s,l)=>s+quoteData.recipes.dessert[l.r][1]*l.q,0),cost=products+(+document.querySelector('#tableSetup').value||0)+(+document.querySelector('#tableDelivery').value||0);let price=Math.round(cost/.48);price=Math.round(price*(1-(+document.querySelector('#tableDiscount').value||0)/100));document.querySelector('#tableSummary').innerHTML=`<h3>Resumen</h3>${lines.map(l=>`<div class="summary-line"><span>${quoteData.recipes.dessert[l.r][0]} × ${l.q}</span><b>${qmoney(quoteData.recipes.dessert[l.r][1]*l.q)}</b></div>`).join('')}<div class="summary-line"><span>Costo estimado</span><b>${qmoney(cost)}</b></div><div class="summary-line"><span>Ganancia</span><b>${qmoney(price-cost)}</b></div><div class="summary-total"><span>Total</span><strong>${qmoney(price)}</strong></div><button class="primary full" onclick="toast('Cotización guardada')">Guardar cotización</button>`}document.querySelector('#addDessert').onclick=()=>{lines.push({r:0,q:12});draw()};['tableSetup','tableDelivery','tableDiscount'].forEach(id=>document.querySelector('#'+id).addEventListener('input',calc));draw();
};

views.quotes=function(){title.textContent='Cotizador';c.innerHTML=`<div class="section-head"><div><h1>Cotizador</h1><p class="muted">Similar a tu sistema actual, pero simplificado para el cliente.</p></div><button class="secondary" onclick="configureProduct()">+ Configurar producto</button></div><div class="notice"><b>Las recetas son de cada negocio.</b> Aquí solo se configura cómo se usan en cada producto.</div><div class="templates">${quoteData.products.map(p=>`<div class="card template"><div class="template-top"><span class="badge">${p.type==='cake'?'Pastel':p.type==='cheese'?'Cheesecake':'Mesa de postres'}</span><button class="link-btn" onclick="configureProduct('${p.id}')">Configurar</button></div><h3>${p.name}</h3><p class="muted">Margen objetivo ${p.margin}%</p><button class="primary full" onclick="${p.type==='cake'?'cakeQuote()':p.type==='cheese'?'cheesecakeQuote()':'dessertTableQuote()'}">Cotizar</button></div>`).join('')}</div>`};
