self.addEventListener('install',e=>self.skipWaiting());
self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));
self.addEventListener('fetch',e=>{
  const u=new URL(e.request.url);
  const isHome=u.origin===location.origin&&(u.pathname==='/matchday/'||u.pathname==='/matchday/index.html');
  if(!isHome||e.request.mode!=='navigate')return;
  e.respondWith(fetch(e.request,{cache:'no-store'}).then(async r=>{
    let html=await r.text();
    html=html.replace('<button class="btn primary full" disabled>Encontrar una cita — próximamente</button>','<button class="btn primary full" onclick="location.href=\'date-matcher.html\'">Encontrar nuestra cita ❤️</button>');
    const oldEnergy='<div class="row"><div class="card"><div class="kicker">Tu energía</div><div class="energy" id="myEnergy"><button class="light g" data-v="green"></button><button class="light y" data-v="yellow"></button><button class="light r" data-v="red"></button></div><input class="field" id="energyNote" placeholder="¿Cómo te sientes?"></div><div class="card"><div class="kicker">Su energía</div><div id="partnerEnergy" style="font-size:38px;margin-top:8px">—</div><div class="mini" id="partnerEnergyNote">Sin actualizar</div></div></div>';
    const newEnergy='<div class="sectionTitle">¿Cómo estamos hoy? ♡</div><div class="card energyPanel"><div class="kicker">Tu mood de hoy</div><div class="energyIntro">Toca lo que más se parezca a cómo estás. Así tu persona sabe cómo acercarse contigo.</div><div class="energy energyChoices" id="myEnergy"><button class="light g energyChoice" data-v="green"><span class="energyEmoji">✨</span><span class="energyCopy"><strong>Con ganas</strong><small>Traigo energía para vernos, platicar o hacer plan.</small></span></button><button class="light y energyChoice" data-v="yellow"><span class="energyEmoji">🌙</span><span class="energyCopy"><strong>Suavecito</strong><small>Ando cansado; quiero algo tranquilo y sin presión.</small></span></button><button class="light r energyChoice" data-v="red"><span class="energyEmoji">🫶</span><span class="energyCopy"><strong>Necesito recargar</strong><small>Estoy saturado; me ayuda descansar, espacio o apapacho.</small></span></button></div><div class="energyQuestion">¿Quieres decir algo más?</div><input class="field" id="energyNote" placeholder="Ej. quiero apapacho, necesito silencio, sí quiero verte pero tranqui…"></div><div class="card partnerMoodCard"><div class="kicker">El mood de tu persona</div><div class="partnerMood" id="partnerEnergy" style="font-size:38px;margin-top:8px">—</div><div class="partnerMoodLabel" id="partnerMoodLabel">Aún no ha elegido cómo está hoy.</div><div class="mini partnerNote" id="partnerEnergyNote">Sin actualizar</div></div>';
    html=html.replace(oldEnergy,newEnergy);
    const energyCss='<style id="energy-v2-css">.energyPanel{background:linear-gradient(145deg,#fffdfa,#fff7f5)}.energyIntro{font-size:13px;color:var(--muted);line-height:1.45;margin:8px 0 14px}.energyChoices{display:grid!important;grid-template-columns:1fr!important;gap:9px!important;margin:10px 0 14px!important}.energyChoice{width:100%!important;height:auto!important;min-height:72px!important;border-radius:18px!important;padding:12px 13px!important;opacity:1!important;display:flex!important;align-items:center!important;gap:12px!important;text-align:left!important;background:white!important;border:1px solid var(--line)!important;box-shadow:none!important;color:var(--ink)!important;transition:.18s transform,.18s border,.18s background!important}.energyChoice:active{transform:scale(.985)}.energyChoice.on{border:2px solid var(--cherry)!important;background:#fff4f3!important;box-shadow:0 7px 18px rgba(169,70,82,.10)!important}.energyChoice.g.on{border-color:var(--green)!important;background:#f3faf6!important}.energyChoice.y.on{border-color:var(--yellow)!important;background:#fff9e9!important}.energyChoice.r.on{border-color:var(--red)!important;background:#fff2f2!important}.energyEmoji{font-size:28px;line-height:1}.energyCopy{display:flex;flex-direction:column;gap:3px}.energyCopy strong{font-family:Georgia,serif;font-size:17px;color:var(--deep)}.energyCopy small{font-size:11px;line-height:1.35;color:var(--muted)}.energyQuestion{font-size:12px;font-weight:800;margin-top:6px}.partnerMoodCard{text-align:center;background:linear-gradient(145deg,#fff8f5,#f8eeee)}.partnerMood{font-size:44px!important}.partnerMood[data-level="green"]:after{content:"  Con ganas";font:20px Georgia;color:#587e69}.partnerMood[data-level="yellow"]:after{content:"  Suavecito";font:20px Georgia;color:#8e722e}.partnerMood[data-level="red"]:after{content:"  Recargando";font:20px Georgia;color:#955258}.partnerMoodLabel{font-size:12px;color:var(--muted);margin:5px 0 10px}.partnerNote{background:white;border:1px solid var(--line);border-radius:14px;padding:10px;margin-top:8px;color:var(--ink)}</style>';
    html=html.replace('</head>',energyCss+'</head>');
    const energyScript='<script id="energy-v2-js">(()=>{const el=document.getElementById("partnerEnergy"),label=document.getElementById("partnerMoodLabel");if(!el)return;const sync=()=>{const t=el.textContent.trim();let lvl=t.includes("🟢")?"green":t.includes("🟡")?"yellow":t.includes("🔴")?"red":"";if(lvl)el.dataset.level=lvl;else delete el.dataset.level;if(label)label.textContent=lvl==="green"?"Tiene energía y está abierto a plan o conversación.":lvl==="yellow"?"Anda cansado; mejor algo tranquilo y con paciencia.":lvl==="red"?"Está saturado; no significa enojo contigo. Mejor apoyo sin presión.":"Aún no ha elegido cómo está hoy."};new MutationObserver(sync).observe(el,{childList:true,subtree:true,characterData:true});sync()})();</script>';
    html=html.replace('</body>',energyScript+'</body>');
    return new Response(html,{status:r.status,statusText:r.statusText,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});
  }).catch(()=>fetch(e.request)));
});