self.addEventListener('install',e=>self.skipWaiting());
self.addEventListener('activate',e=>e.waitUntil(self.clients.claim()));
self.addEventListener('fetch',e=>{
  const u=new URL(e.request.url);
  const isHome=u.origin===location.origin&&(u.pathname==='/matchday/'||u.pathname==='/matchday/index.html');
  if(!isHome||e.request.mode!=='navigate')return;
  e.respondWith(fetch(e.request,{cache:'no-store'}).then(async r=>{
    let html=await r.text();
    html=html.replace('<button class="btn primary full" disabled>Encontrar una cita — próximamente</button>','<button class="btn primary full" onclick="location.href=\'date-matcher.html\'">Encontrar nuestra cita ❤️</button>');

    const oldEnergy='<div class="row"><div class="card"><div class="kicker">Tu energía</div><div class="energy" id="myEnergy"><button class="light g" data-v="green"></button><button class="light y" data-v="yellow"></button><button class="light r" data-v="red"></button></div><input class="field" id="energyNote" placeholder="¿Cómo te sientes?"></div><div class="card"><div class="kicker">Su energía</div><div id="partnerEnergy" style="font-size:38px;margin-top:8px">—</div><div class="mini" id="partnerEnergyNote">Sin actualizar</div></div></div>';
    const newEnergy='<div class="sectionTitle">¿Cómo estamos hoy? ♡</div><div class="card energyPanel"><div class="kicker">Tu mood de hoy</div><div class="energyIntro">Toca lo que más se parezca a cómo estás. Así tu persona sabe cómo acercarse contigo.</div><div class="energy energyChoices" id="myEnergy"><button class="light g energyChoice" data-v="green"><span class="energyEmoji">✨</span><span class="energyCopy"><strong>Con ganas</strong><small>Traigo energía para vernos, platicar o hacer plan.</small></span></button><button class="light y energyChoice" data-v="yellow"><span class="energyEmoji">🌙</span><span class="energyCopy"><strong>Suavecito</strong><small>Ando cansado; quiero algo tranquilo y sin presión.</small></span></button><button class="light r energyChoice" data-v="red"><span class="energyEmoji">🫶</span><span class="energyCopy"><strong>Necesito recargar</strong><small>Estoy saturado; me ayuda descansar, espacio o apapacho.</small></span></button></div><div class="energyQuestion">¿Quieres decir algo más?</div><input class="field" id="energyNote" placeholder="Ej. quiero apapacho, necesito silencio, sí quiero verte pero tranqui…"></div><div class="card partnerMoodCard"><div class="kicker">El mood de tu persona</div><div class="partnerMood" id="partnerEnergy" style="font-size:38px;margin-top:8px">—</div><div class="partnerMoodLabel" id="partnerMoodLabel">Aún no ha elegido cómo está hoy.</div><div class="mini partnerNote" id="partnerEnergyNote">Sin actualizar</div></div>';
    html=html.replace(oldEnergy,newEnergy);

    const extraCss='<style id="matchday-hotfix-css">.energyPanel{background:linear-gradient(145deg,#fffdfa,#fff7f5)}.energyIntro{font-size:13px;color:var(--muted);line-height:1.45;margin:8px 0 14px}.energyChoices{display:grid!important;grid-template-columns:1fr!important;gap:9px!important;margin:10px 0 14px!important}.energyChoice{width:100%!important;height:auto!important;min-height:72px!important;border-radius:18px!important;padding:12px 13px!important;opacity:1!important;display:flex!important;align-items:center!important;gap:12px!important;text-align:left!important;background:white!important;border:1px solid var(--line)!important;box-shadow:none!important;color:var(--ink)!important}.energyChoice.on{border:2px solid var(--cherry)!important;background:#fff4f3!important}.energyEmoji{font-size:28px}.energyCopy{display:flex;flex-direction:column;gap:3px}.energyCopy strong{font-family:Georgia,serif;font-size:17px;color:var(--deep)}.energyCopy small{font-size:11px;line-height:1.35;color:var(--muted)}.partnerMoodCard{text-align:center;background:linear-gradient(145deg,#fff8f5,#f8eeee)}.partnerNote{background:white;border:1px solid var(--line);border-radius:14px;padding:10px;margin-top:8px;color:var(--ink)}.legend{display:flex;gap:12px;flex-wrap:wrap;margin-top:10px;font-size:10px;color:var(--muted)}.legend span:before{content:"•";font-size:20px;vertical-align:-2px;margin-right:3px;color:var(--rose)}.legend span:last-child:before{content:"♡";font-size:13px;color:var(--cherry)}.mochiHome{display:flex;align-items:center;gap:14px;cursor:pointer;background:linear-gradient(145deg,#fff9f7,#f6e7e7)}.mochiFace{font-size:52px;animation:mochiBob 2.8s ease-in-out infinite}.mochiCopy{flex:1}.mochiCopy strong{display:block;font:20px Georgia;color:var(--deep);margin:2px 0}.mochiArrow{font-size:24px;color:var(--cherry)}@keyframes mochiBob{50%{transform:translateY(-4px)}}</style>';
    html=html.replace('</head>',extraCss+'</head>');

    const hotfixScript='<script id="matchday-hotfix-js">(()=>{function installMochi(){if(document.getElementById("mochiHome"))return;const calTitle=[...document.querySelectorAll(".sectionTitle")].find(x=>x.textContent.includes("Nuestro calendario"));if(!calTitle)return;const card=document.createElement("div");card.id="mochiHome";card.className="card mochiHome";card.innerHTML="<div class=\"mochiFace\">🐻</div><div class=\"mochiCopy\"><div class=\"kicker\">Nuestra racha 🔥</div><strong>Mochi</strong><div class=\"mini\">Tu mascotita de MATCHDAY · toca para verla ♡</div></div><div class=\"mochiArrow\">›</div>";card.onclick=()=>location.href="mascota.html";calTitle.parentNode.insertBefore(card,calTitle)}function restoreLegend(){const cal=document.getElementById("calendar");if(!cal||cal.parentElement.querySelector(".legend"))return;const legend=document.createElement("div");legend.className="legend";legend.innerHTML="<span>Horario</span><span>Match Time</span>";cal.after(legend)}function restoreCalendar(){if(typeof window.matchForDay!=="function"||!document.getElementById("calendar"))return;window.renderCalendar=function(){let y=calDate.getFullYear(),m=calDate.getMonth();document.getElementById("calTitle").textContent=new Date(y,m,1).toLocaleDateString("es-MX",{month:"long",year:"numeric"}).replace(/^./,c=>c.toUpperCase());let first=new Date(y,m,1),offset=(first.getDay()+6)%7,last=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate(),html="",today=new Date();for(let i=0;i<42;i++){let num,cls="day",date;if(i<offset){num=prev-offset+i+1;cls+=" out";date=new Date(y,m-1,num)}else if(i>=offset+last){num=i-offset-last+1;cls+=" out";date=new Date(y,m+1,num)}else{num=i-offset+1;date=new Date(y,m,num)}let dow=date.getDay(),has=allSchedules.some(s=>+s.day_of_week===dow),match=partnerId&&matchForDay(dow).length;if(has)cls+=" hasBusy";if(match)cls+=" match";if(date.toDateString()===today.toDateString())cls+=" today";html+=`<div class="${cls}">${num}</div>`}document.getElementById("calendar").innerHTML=html;restoreLegend()};window.renderCalendar()}function syncPartnerMood(){const el=document.getElementById("partnerEnergy"),label=document.getElementById("partnerMoodLabel");if(!el)return;const sync=()=>{const t=el.textContent.trim();let lvl=t.includes("🟢")?"green":t.includes("🟡")?"yellow":t.includes("🔴")?"red":"";if(label)label.textContent=lvl==="green"?"Tiene energía y está abierto a plan o conversación.":lvl==="yellow"?"Anda cansado; mejor algo tranquilo y con paciencia.":lvl==="red"?"Está saturado; no significa enojo contigo. Mejor apoyo sin presión.":"Aún no ha elegido cómo está hoy."};new MutationObserver(sync).observe(el,{childList:true,subtree:true,characterData:true});sync()};setTimeout(()=>{installMochi();restoreCalendar();restoreLegend();syncPartnerMood()},50)})();</script>';
    html=html.replace('</body>',hotfixScript+'</body>');
    return new Response(html,{status:r.status,statusText:r.statusText,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});
  }).catch(()=>fetch(e.request)));
});